TOKEN=""
admin_id=["204596506"]
help="Send 'add + username' to subscribe to Instagram user\n Send 'del + username' to unsubscribe Instagram user"
start="Welkome\n Send 'add + username' to subscribe to Instagram user\n Send 'del + username' to unsubscribe Instagram user"
stopBot="You killed the Bot"
logmsgOn="Logs enabled"
logmsgOff="Logs disabled"
logmsgInstagramCheck="One more Instagram check done"
logmsgBotOff="Bot turned off"
